config/routes.rb
Rails.application.routes.draw do
  resources :products
  resources :mushrooms
  
  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/mushroom.rb
class Mushroom < ApplicationRecord
  belongs_to :user
end

app/models/product.rb
class Product < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/mushrooms_controller.rb
class MushroomsController < ApplicationController

  def index; end
  
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy ]

  # GET /products or /products.json
  def index
    @products = Product.all
  end

  # GET /products/1 or /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:name, :price, :stock)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/home/index.html.erb
<div class="w-full flex flex-col">
  <h1 class="text-5xl mt-32 text-center font-bold text-transparent bg-gradient-to-r from-pink-400 to-blue-600 bg-clip-text ">Welcome to MaineShrooms </h1>
  <div class="flex justify-center items-center h-80 w-full md:w-2/3 lg:w-1/2 mx-auto">
    <a href="<%= products_path %>" class="px-6 py-1 text-purple-400 border-2 border-purple-400"> Get mushrooms online </a>
    <a href="<%= mushrooms_path %>" class="ml-4 px-6 py-1 border-b-2 border-gray-900 hover:border-gray-600"> Learn about mushrooms </a>
  </div>
</div>

app/views/layouts/_alerts.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MushroomsForSale</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbo-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbo-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbo-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/alerts" %>
    <%= yield %>
  </body>
</html>

app/views/products/_form.html.erb
<%= form_with(model: product) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="field">
    <%= form.label :stock %>
    <%= form.number_field :stock %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<div class="w-full flex flex-col bg-green-600 pt-40">
  <div class="h-20 py-3 w-full md:w-3/4 mx-auto bg-gray-300 flex">
    <%= form_for "/products/search", html: { class: "w-full flex items-center"} do |form| %>
      <div class="flex flex-col justify-between h-full w-full mx-4">
        <%= form.label :name_of_mushroom %>
        <%= form.text_field :mushroom_name, placeholder: "Example: Turkey tail or Trimetes versicolor", class: "w-full outline-none ring-2 focus:ring-green-600 pl-1" %>
      </div>
      <div class="flex flex-col justify-between h-full w-full mx-4">
        <%= form.label :by_location %>
        <%= form.text_field :location, placeholder: "123 Main St, Bangor ME", class: "w-full outline-none ring-2 focus:ring-green-600 pl-1" %>
      </div>
      <div class="h-full w-full md:w-1/2 flex items-end">
        <%= form.submit "Search", class: "bg-transparent mx-auto px-6 py-2 border-b-2 border-green-600 text-gray-700" %>
      </div>
    <% end %>
  </div>
  <div class="h-screen w-full md:w-3/4 mx-auto bg-gray-100"
</div>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>Stock:</strong>
  <%= @product.stock %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>